baseURL: https://cobbman.com/
languageCode: en-us
title: cobbman.com
theme: hugo-PaperMod

menu:
    main:
        - identifier: archives
          name: archives
          url: /archives/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: dev.to profile
          name: dev.to
          url: https://dev.to/cobb
          weight: 30

params:
  defaultTheme: dark
  ShowReadingTime: true
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  homeInfoParams:
    Title: William Cobb
    Content: Full-stack Software Developer. Hobbyist writer and photographer.
  socialIcons: # optional
    - name: "github"
      url: 'https://github.com/cobbman'
    - name: 'twitter'
      url: 'https://twitter.com/william_cobb'
    - name: 'dev'
      url: 'https://dev.to/cobb'
